### ISSUE TITLE
Graph's adj list

### ISSUE THREAD

**Issue by jpapaioan** [jinhongchen/Chen_Alvey_Garner_CSCI2270_FinalProject#13]
why is everything connected to everything? This makes the Dijkstra's algorithm unnecessary and trivial. Should have limited the connectivity, it doesn't make sense that east coast cities and west coast cities are directly connected.

**Comment by Jual6332** [comment]
The correct text file has been re-uploaded with effects we originally intended. All neighboring cities within 2000 miles of another city are direct, while cities farther than this distance must take a less direct route, chosen by the Dijkstra's algorithm. Thank you for the update. West Coast cities are not directly connected to East Coast cities given the reupload of the text file.
