### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by jpapaioan** [jinhongchen/Chen_Alvey_Garner_CSCI2270_FinalProject#14]
your README file is outdated and doesn't contain accurate information as to what the program does. There is no add service function and in fact, there doesn't seem to be any services whatsoever in the vertices, gas stations, restaurants etc.

**Comment by Jual6332** [comment]
Our README file is up-to-date with our goals and all required project criteria. The program allows a user to "Plan A Trip", and the program calculates the necessary services to stop at along the way. Gas Stations, restaurants, and hotels allow the user to stop (whichever is required) along the way to make their trip feasible. Driving is intended as the method for transportation.
